language: go
go:
  - 1.11.x

# Only clone the most recent commit.
git:
  depth: 1

# Don't email me the results of the test runs.
notifications:
  email: false

before_script:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.12.5

script:
  - golangci-lint run       # run a bunch of code checkers/linters in parallel
  - go test -v -race ./...  # Run all the tests with the race detector enabled

jobs:
  include:
    - stage: release tagged version
      if: tag IS present
      script:
        - echo "Travis tag $TRAVIS_TAG"
        - export ALIAS=`echo $TRAVIS_COMMIT | cut -c 1-7`
        - export TAG=`echo $TRAVIS_TAG | sed 's/\./-/g' | sed 's/.*/v&/'`
        # Build and release to Docker Hub
        - docker login -u $DOCKER_USER -p $DOCKER_PASS
        - export REPO=$DOCKER_REPO
        - docker build -f Dockerfile -t $REPO:$TRAVIS_TAG .
        - docker tag $REPO:$TRAVIS_TAG $REPO:latest
        - docker push $REPO:$TRAVIS_TAG
        - docker push $REPO